[[aerospike.repositories]]
= Aerospike Repositories

[[aerospike.repositories.intro]]
== Introduction

One of the main goals of the Spring Data is to significantly reduce the amount of boilerplate code required to implement
data access layers for various persistence stores.

One of the core interfaces of Spring Data is `Repository`.
This interface acts primarily to capture the types to work with and to help user to discover interfaces that
extend Repository.

In other words, it allows user to have basic and complicated queries without writing the implementation.
This builds on the
link:https://docs.spring.io/spring-data/rest/reference/data-commons/repositories.html[Core Spring Data Repository Support],
so make sure you've got a sound understanding of this concept.

[[aerospike.repositories.usage]]
== Usage

To access entities stored in Aerospike you can leverage repository support that eases implementing those quite
significantly. To do so, define a mapped entity and a repository interface.

.Sample movie entity
====
[source,java]
----
include::{examples-java}/org/springframework/data/aerospike/examples/blocking/crud/entity/MovieDocument.java[tag=blocking-crud-entity]
----
====
We have a quite simple domain object here. The default serialization mechanism used in `AerospikeTemplate`
(which is backing the repository support) regards properties named `id` as document id.
Currently we support `String` and `long` as id-types.

.Basic repository interface to persist movie entities
====
[source]
----
include::{examples-java}/org/springframework/data/aerospike/examples/blocking/crud/repository/MovieRepository.java[tag=blocking-crud-repository]
----
====

Right now this interface simply serves typing purposes, but we will add additional methods to it later.

Runnable framework-owned source examples are available for
link:https://github.com/aerospike/spring-data-aerospike/blob/main/examples/src/main/java/org/springframework/data/aerospike/examples/blocking/crud/BlockingRepositoryCrudExample.java[blocking repository CRUD],
link:https://github.com/aerospike/spring-data-aerospike/blob/main/examples/src/main/java/org/springframework/data/aerospike/examples/blocking/query/SecondaryIndexQueryExample.java[indexed derived queries],
link:https://github.com/aerospike/spring-data-aerospike/blob/main/examples/src/main/java/org/springframework/data/aerospike/examples/blocking/indexed/IndexedAnnotationExample.java[`@Indexed` startup index creation], and
link:https://github.com/aerospike/spring-data-aerospike/blob/main/examples/src/main/java/org/springframework/data/aerospike/examples/blocking/declaredquery/BlockingDeclaredQueryExample.java[declared DSL queries].
They can be run from the repository with `./examples/run_examples all --hosts localhost:3000 --namespace test`.

We are going to use the `@EnableAerospikeRepositories` annotation. If no base package is configured the infrastructure
will scan the package of the annotated configuration class.

.JavaConfig for repositories
====
[source,java]
----
include::{examples-java}/org/springframework/data/aerospike/examples/blocking/crud/config/AerospikeConfiguration.java[tag=blocking-crud-configuration]
----
====

`MovieRepository` extends `AerospikeRepository`, which itself extends `PagingAndSortingRepository` and
`CrudRepository`. That gives repository instances inherited CRUD operations as well as paginated and sorted access
methods. For source-backed pagination and sorting examples, see <<pagination_and_sorting>>.

[[aerospike.repositories.queries]]
== Query methods

Most of the data access operations you usually trigger on a repository result in a query being executed against
the Aerospike databases. Defining such a query is just a matter of declaring a method on the repository interface

.Repository with query methods
====
[source,java]
----
include::{examples-java}/org/springframework/data/aerospike/examples/blocking/querymethods/repository/QueryMethodsMovieRepository.java[tag=blocking-query-methods-repository]
----
====
[[aerospike.repositories.example]]
== Examples

The following snippets are taken from the runnable `blocking-crud` example.

.Save and read one entity
[source,java]
----
include::{examples-java}/org/springframework/data/aerospike/examples/blocking/crud/BlockingRepositoryCrudExample.java[tag=blocking-crud-save-read,indent=0]
----

.Save and read several entities
[source,java]
----
include::{examples-java}/org/springframework/data/aerospike/examples/blocking/crud/BlockingRepositoryCrudExample.java[tag=blocking-crud-batch-save-read,indent=0]
----

.Count and read all entities
[source,java]
----
include::{examples-java}/org/springframework/data/aerospike/examples/blocking/crud/BlockingRepositoryCrudExample.java[tag=blocking-crud-count-find-all,indent=0]
----

.Delete entities
[source,java]
----
include::{examples-java}/org/springframework/data/aerospike/examples/blocking/crud/BlockingRepositoryCrudExample.java[tag=blocking-crud-delete,indent=0]
----

