[[aerospike.projections]]
= Projections with Aerospike

Spring Data Aerospike supports Projections, a mechanism that allows you to fetch only relevant fields from Aerospike for a particular use case. This results in better performance, less network traffic, and a better understanding of what is required for the rest of the flow.

For more details, refer to Spring Data documentation: link:https://docs.spring.io/spring-data/rest/reference/data-commons/repositories/projections.html[Projections].

For example, consider a movie document:

[source, java]
----
include::{examples-java}/org/springframework/data/aerospike/examples/blocking/projection/entity/ProjectedMovieDocument.java[tag=projection-entity]
----

The use case might call for a compact result that shows only the `title` and `releaseYear` fields while the full
document still stores more data.

A simple projection of this object might be:
[source, java]
----
include::{examples-java}/org/springframework/data/aerospike/examples/blocking/projection/dto/MovieSummary.java[tag=projection-dto]
----

Now the repository interface can be extended to return this projection:

[source, java]
----
include::{examples-java}/org/springframework/data/aerospike/examples/blocking/projection/repository/ProjectionMovieRepository.java[tag=projection-repository]
----

The repository can return a projection from a dedicated method or from a dynamic target-class method:

[source, java]
----
include::{examples-java}/org/springframework/data/aerospike/examples/blocking/projection/ProjectionExample.java[tag=projection-usage,indent=0]
----

Spring Data maps the returned records into `MovieSummary`, reducing the data exposed to the rest of the application.

A blog post with more details on projections can be found https://medium.com/aerospike-developer-blog/spring-data-aerospike-projections-951382bc07b5[here].
