[[aerospike.custom-converters]]
= Aerospike Custom Converters

Spring type converters are components used to convert data between different types, particularly when interacting with databases or binding data from external sources. They facilitate seamless transformation of data, such as converting between String and database-specific types (e.g., LocalDate to DATE or String to enumerations).

For more details, see link:https://docs.spring.io/spring-framework/reference/core/validation/convert.html[Spring Type Conversion].

Spring provides a set of default type converters for common conversions. Spring Data Aerospike has its own built-in converters in `DateConverters` and `AerospikeConverters` classes.

However, in certain cases, custom converters are necessary to handle specific logic or custom serialization requirements. Custom converters allow developers to define precise conversion rules, ensuring data integrity and compatibility between application types and database representations.

In order to add a custom converter you can leverage Spring's `Converter` SPI to implement type conversion logic and override `customConverters()` method available in `AerospikeDataConfigurationSupport`.

Here is an example:

[source,java]
----
include::{examples-java}/org/springframework/data/aerospike/examples/blocking/converters/config/CustomConvertersAerospikeConfiguration.java[tag=custom-converters-registration,indent=0]
----

The converters themselves implement Spring's `Converter` SPI:

[source,java]
----
include::{examples-java}/org/springframework/data/aerospike/examples/blocking/converters/entity/ConverterOrderId.java[tag=custom-converters-writing-converter,indent=0]
----

[source,java]
----
include::{examples-java}/org/springframework/data/aerospike/examples/blocking/converters/entity/ConverterOrderId.java[tag=custom-converters-reading-converter,indent=0]
----

The converted id can then be used with regular template operations:

[source,java]
----
include::{examples-java}/org/springframework/data/aerospike/examples/blocking/converters/BlockingCustomConvertersExample.java[tag=custom-converters-usage,indent=0]
----

For more examples see the link:https://github.com/aerospike/spring-data-aerospike-demo/blob/main/asciidoc/custom-converters.adoc[Custom Converters Guide] in the demo repository.
