[[aerospike.reactive.repositories]]
= Reactive Aerospike Repositories

[[aerospike-reactive-repo-intro]]
== Introduction

This chapter will point out the specialties for reactive repository support for Aerospike. This builds on the core
repository support explained in <<aerospike.repositories, repositories>>. So make sure you've got
a sound understanding of the basic concepts explained there.

[[aerospike.reactive.repositories.libraries]]
== Reactive Composition Libraries

The reactive space offers various reactive composition libraries. The most common library is
https://projectreactor.io/[Project Reactor].

Spring Data Aerospike is built on top of the
https://github.com/aerospike/aerospike-client-java-reactive[Aerospike Reactor Java Client Library].
To provide maximal interoperability it relies on the https://www.reactive-streams.org/[Reactive Streams] initiative.
Static APIs, such as `ReactiveAerospikeOperations`, are provided by using Project Reactor's `Flux` and `Mono` types.
Project Reactor offers various adapters to convert reactive wrapper types  (`Flux` to `Observable` and vice versa).

Spring Data's Repository abstraction is a dynamic API, mostly defined by you and your requirements as you declare
query methods. Reactive Aerospike repositories can be implemented by using Project Reactor wrapper types
by extending from the following library-specific repository interface:

* `ReactiveAerospikeRepository`


[[aerospike-reactive-repo-usage]]
== Usage

To access domain entities stored in an Aerospike you can use our sophisticated repository support that eases
implementing those quite significantly. To do so, create an interface similar to your repository.
Before you can do that, though, you need an entity, such as the entity defined in the following example:

.Sample reactive movie entity
====
[source,java]
----
include::{examples-java}/org/springframework/data/aerospike/examples/reactive/crud/entity/ReactiveMovieDocument.java[tag=reactive-crud-entity]
----
====
We have a quite simple domain object here. The default serialization mechanism used in `ReactiveAerospikeTemplate`
(which is backing the repository support) regards properties named id as document ID. Currently, we support
`String` and `long` as id-types. The following example shows how to create an interface that defines queries
against the `ReactiveMovieDocument` object from the preceding example:

.Basic repository interface to persist reactive movie entities
====
[source]
----
include::{examples-java}/org/springframework/data/aerospike/examples/reactive/crud/repository/ReactiveMovieRepository.java[tag=reactive-crud-repository]
----
====

Right now this interface simply serves typing purposes but we will add additional methods to it later.

For a runnable source-backed example of reactive repository CRUD operations, see
link:https://github.com/aerospike/spring-data-aerospike/blob/main/examples/src/main/java/org/springframework/data/aerospike/examples/reactive/crud/ReactiveRepositoryCrudExample.java[`ReactiveRepositoryCrudExample`].
It can be run from the repository with `./examples/run_examples reactive-crud --hosts localhost:3000 --namespace test`.

For Java configuration, use the `@EnableReactiveAerospikeRepositories` annotation. The annotation carries the base
packages attribute. These base packages are to be scanned for interfaces extending `ReactiveAerospikeRepository`
and create Spring beans for each of them found. If no base package is configured, the infrastructure scans the package
of the annotated configuration class.

The following listing shows how to use Java configuration for a repository:

.Java configuration for repositories
====
[source,java]
----
include::{examples-java}/org/springframework/data/aerospike/examples/reactive/crud/config/ReactiveAerospikeConfiguration.java[tag=reactive-crud-configuration]
----
====

As our domain repository extends `ReactiveAerospikeRepository` it provides CRUD operations that return Reactor
publishers. The source-backed examples below show repository usage with `Mono` and `Flux` return values.

[[aerospike.reactive.repositories.queries]]
== Query methods

Most of the data access operations you usually trigger on a repository result in a query being executed against
the Aerospike databases. Defining such a query is just a matter of declaring a method on the repository interface

.Reactive repository with query methods
====
[source,java]
----
include::{examples-java}/org/springframework/data/aerospike/examples/reactive/querymethods/repository/ReactiveQueryMethodsMovieRepository.java[tag=reactive-query-methods-repository]
----
====

[[aerospike.reactive.repositories.example]]
== Examples

The following snippets are taken from the runnable `reactive-crud` example.

.Save and read one entity
[source,java]
----
include::{examples-java}/org/springframework/data/aerospike/examples/reactive/crud/ReactiveRepositoryCrudExample.java[tag=reactive-crud-save-read,indent=0]
----

.Save and read several entities
[source,java]
----
include::{examples-java}/org/springframework/data/aerospike/examples/reactive/crud/ReactiveRepositoryCrudExample.java[tag=reactive-crud-batch-save-read,indent=0]
----

.Count and read all entities
[source,java]
----
include::{examples-java}/org/springframework/data/aerospike/examples/reactive/crud/ReactiveRepositoryCrudExample.java[tag=reactive-crud-count-find-all,indent=0]
----

.Delete entities
[source,java]
----
include::{examples-java}/org/springframework/data/aerospike/examples/reactive/crud/ReactiveRepositoryCrudExample.java[tag=reactive-crud-delete,indent=0]
----

