[[caching]]
= Caching

Caching is the process of storing data in a cache or temporary storage location, usually to improve application
performance and make data access faster.

The caching process also provides an efficient way to reuse previously retrieved or computed data.
The cache is used to reduce the need for accessing the underlying storage layer which is slower.

Spring Cache with Aerospike database allows you to use annotations such as `@Cacheable`, `@CachePut`
and `@CacheEvict` that provide a fully managed cache store using Aerospike database.

== Introduction

In this example, we are going to use the annotations on `BlockingCachingMovieService` methods to create/read/update
and delete movie data from the cache.

If a `CachedMovie` is stored in the cache, calling a method with `@Cacheable` annotation will fetch the movie from
the cache instead of executing the method’s body responsible for the underlying data lookup.

If the `CachedMovie` does not exist in the cache, the movie data will be fetched from the database and put in the cache
for later usage (a “cache miss”).

With Spring Cache and Aerospike database, we can achieve that with only a few lines of code.

== Motivation

Let’s say that we are using another database as our main data store.
We don’t want to fetch the results from it every time we request the data, instead, we want to get the data from
a cache layer.

There is a number of benefits of using a cache layer, here are some of them:

[arabic]
. Performance: Aerospike can work purely in RAM but reading a record from Aerospike in Hybrid Memory (primary index
in memory, data stored on Flash drives) is extremely fast as well (~1ms).
. Reduce database load: Moving a significant part of the read load from the main database to Aerospike can help
balance the resources on heavy loads.
. Scalability: Aerospike scales horizontally by adding more nodes to the cluster, scaling a relational database
might be tricky and expensive, so if you are facing a read heavy load you can easily scale up the cache layer.

== Example

We will not use an actual database as our main data store for this example. Instead, the example simulates a database
read by returning a specific `CachedMovie`.

=== Configuration

The runnable example uses `BlockingCachingAerospikeConfiguration`, which extends `AbstractAerospikeDataConfiguration`
and enables Spring cache support. `AbstractAerospikeDataConfiguration` supplies the `IAerospikeClient` and
`MappingAerospikeConverter`; the example declares the cache-specific bean:

[source,java]
----
include::{examples-java}/org/springframework/data/aerospike/examples/blocking/caching/config/BlockingCachingAerospikeConfiguration.java[tag=caching-cache-manager,indent=0]
----

[[cache-example-configuration-AerospikeCacheManager]]
=== AerospikeCacheManager

The heart of the cache layer, to define an `AerospikeCacheManager` you need:

[arabic]
. `IAerospikeClient`, supplied by `AbstractAerospikeDataConfiguration`.
. `MappingAerospikeConverter`, supplied by the mapping configuration.
. `AerospikeCacheKeyProcessor`, used to map Spring cache keys to Aerospike keys.
. `AerospikeCacheConfiguration`, a default cache configuration that applies when creating
new caches.
Cache configuration contains a namespace, a set (null by default meaning write directly to the namespace w/o
specifying a set) and an expirationInSeconds (AKA TTL, default is 0 meaning use Aerospike server’s default).

NOTE: A cache name is only a link to the cache configuration.
The runnable example configures a dedicated `sda_examples_cache_entries` set instead of leaving the cache set null.
That keeps cleanup constrained to records owned by the example.

=== Objects

==== CachedMovie

[source,java]
----
include::{examples-java}/org/springframework/data/aerospike/examples/blocking/caching/entity/CachedMovie.java[tag=caching-value]
----

=== Cache annotations

==== BlockingCachingMovieService

[source,java]
----
include::{examples-java}/org/springframework/data/aerospike/examples/blocking/caching/BlockingCachingMovieService.java[tag=caching-cacheable,indent=0]
----

[source,java]
----
include::{examples-java}/org/springframework/data/aerospike/examples/blocking/caching/BlockingCachingMovieService.java[tag=caching-cache-put,indent=0]
----

[source,java]
----
include::{examples-java}/org/springframework/data/aerospike/examples/blocking/caching/BlockingCachingMovieService.java[tag=caching-cache-evict,indent=0]
----

The cache annotations require a cache name, declared here through `cacheNames = "movies"`.
The `AerospikeCacheManager` maps that cache name to the configured Aerospike cache storage
(Configuration > <<cache-example-configuration-AerospikeCacheManager, AerospikeCacheManager>>).

=== Usage

The runnable example calls the cached service methods through a Spring-managed bean, so cache advice is applied.

.Cache hit
[source,java]
----
include::{examples-java}/org/springframework/data/aerospike/examples/blocking/caching/BlockingCachingExample.java[tag=caching-cacheable-usage,indent=0]
----

.Cache update
[source,java]
----
include::{examples-java}/org/springframework/data/aerospike/examples/blocking/caching/BlockingCachingExample.java[tag=caching-cache-put-usage,indent=0]
----

.Cache eviction
[source,java]
----
include::{examples-java}/org/springframework/data/aerospike/examples/blocking/caching/BlockingCachingExample.java[tag=caching-cache-evict-usage,indent=0]
----

