= Caching

Caching is the process of storing data in a cache or temporary storage location, usually to improve application performance and make data access faster.

The caching process also provides an efficient way to reuse previously retrieved or computed data. The cache is used to reduce the need for accessing the underlying storage layer that is slower.

Spring Cache with Aerospike database allows you to use annotations such as `@Cacheable`, `@CachePut` and `@CacheEvict` that provide a fully managed cache store using Aerospike database.

== Introduction

In this example we are going to use the annotations on a `UserRepository` class methods to create/read/update and delete user’s data from the cache.

If a `User` is stored in the cache, calling a method with `@Cacheable` annotation will fetch the user from the cache instead of executing the method’s body responsible for the actual user fetch from the database.

If the `User` does not exist in the cache, the user’s data will be fetched from the database and put in the cache for later usages (a “cache miss”).

With Spring Cache and Aerospike database we can achieve that with only few lines of code.

== Motivation

Let’s say that we are using another database as our main data store. We don’t want to fetch the results from it every time we request the data, instead we want to get the data from a cache layer.

There is a number of benefits of using a cache layer, here are some of them:

[arabic]
. Performance: Aerospike can work purely in RAM but reading a record from Aerospike in Hybrid Memory (primary index in memory, data stored on Flash drives) is extremely fast as well (~1ms).
. Reduce database load: Moving a significant part of the read load from the main database to Aerospike can help balance the resources on heavy loads.
. Scalability: Aerospike scales horizontally by adding more nodes to the cluster, scaling a relational database might be tricky and expensive, so if you are facing a read heavy load you can easily scale up the cache layer.

== Example

We will not use an actual database as our main data store for this example, instead we will simulate a database access by printing a simulation message and replace a database read by just returning a specific `User`.

== Configuration
=== AerospikeConfigurationProperties

[source, java]
----
@Data
@Component
@ConfigurationProperties(prefix = "aerospike")
public class AerospikeConfigurationProperties {
private String host;
private int port;
}
----

=== AerospikeConfiguration

[source, java]
----
@Configuration
@EnableConfigurationProperties(AerospikeConfigurationProperties.class)
@Import(value = {MappingAerospikeConverter.class, AerospikeMappingContext.class, AerospikeTypeAliasAccessor.class
        ,AerospikeCustomConversions.class, SimpleTypeHolder.class})
public class AerospikeConfiguration {

    @Autowired
    private MappingAerospikeConverter mappingAerospikeConverter;
    @Autowired
    private AerospikeConfigurationProperties aerospikeConfigurationProperties;

    @Bean(destroyMethod = "close")
    public AerospikeClient aerospikeClient() {
        ClientPolicy clientPolicy = new ClientPolicy();
        clientPolicy.failIfNotConnected = true;
        return new AerospikeClient(clientPolicy, aerospikeConfigurationProperties.getHost(), aerospikeConfigurationProperties.getPort());
    }

    @Bean
    public AerospikeCacheManager cacheManager(AerospikeClient aerospikeClient) {
        AerospikeCacheConfiguration defaultConfiguration = new AerospikeCacheConfiguration("test");
        return new AerospikeCacheManager(aerospikeClient, mappingAerospikeConverter, defaultConfiguration);
    }
}
----

In the AerospikeConfiguration we will create two types of Beans:

==== AerospikeClient

Responsible for accessing an Aerospike database and perform database operations.

[[cache-example-configuration-AerospikeCacheManager]]
==== AerospikeCacheManager

The heart of the cache layer, to define an AerospikeCacheManager you need:

[arabic]
. aerospikeClient (AerospikeClient).
. aerospikeConverter (MappingAerospikeConverter).
. defaultCacheConfiguration (AerospikeCacheConfiguration), a default cache configuration that applies when creating new caches. Cache configuration contains a namespace, a set (null by default meaning write directly to the namespace w/o specifying a set) and an expirationInSeconds (AKA TTL, default is 0 meaning use Aerospike server’s default).
. Optional: initalPerCacheConfiguration (Map<String, AerospikeCacheConfiguration>), You can also specify a map of cache names and matching configuration, it will create the caches with the given matching configuration at the application startup.

NOTE: A cache name is only a link to the cache configuration.

==== Objects

===== User

[source, java]
----
@Data
@Document
@AllArgsConstructor
public class User {
    @Id
    private int id;
    private String name;
    private String email;
    private int age;
}
----

==== Repositories

===== UserRepository

[source, java]
----
@Repository
public class UserRepository {

    @Cacheable(value = "test", key = "#id")
    public Optional<User> getUserById(int id) {
        System.out.println("Simulating a read from the main data store.");
        // In case the id doesn't exist in the cache it will "fetch" jimmy page with the requested id and add it to the cache (cache miss).
        return Optional.of(new User(id, "jimmy page", "jimmy@gmail.com", 77));
    }

    @CachePut(value = "test", key = "#user.id")
    public User addUser(User user) {
        System.out.println("Simulating addition of " + user + " to the main data store.");
        return user;
    }

    @CacheEvict(value = "test", key = "#id")
    public void removeUserById(int id) {
        System.out.println("Simulating removal of " + id + " from the main data store.");
    }
}
----

The cache annotations requires a “value” field, this is the cache name, if the cache name doesn't exist — by passing initialPerCacheConfiguration param when creating a Bean of AerospikeCacheManager in a configuration class, it will configure the cache with the properties of the given defaultCacheConfiguration (Configuration > <<cache-example-configuration-AerospikeCacheManager, AerospikeCacheManager>>).

==== Services

===== UserService

[source, java]
----
@Service
@AllArgsConstructor
public class UserService {

    UserRepository userRepository;

    public Optional<User> readUserById(int id) {
        return userRepository.getUserById(id);
    }

    public User addUser(User user) {
        return userRepository.addUser(user);
    }

    public void removeUserById(int id) {
        userRepository.removeUserById(id);
    }
}
----

==== Controllers

===== UserController

[source, java]
----
@RestController
@AllArgsConstructor
public class UserController {

    UserService userService;

    @GetMapping("/users/{id}")
    public Optional<User> readUserById(@PathVariable("id") Integer id) {
        return userService.readUserById(id);
    }

    @PostMapping("/users")
    public User addUser(@RequestBody User user) {
        return userService.addUser(user);
    }

    @DeleteMapping("/users/{id}")
    public void deleteUserById(@PathVariable("id") Integer id) {
        userService.removeUserById(id);
    }
}
----

==== Add @EnableCaching

===== SimpleSpringbootAerospikeCacheApplication

Add `@EnableCaching` to the class that contains the main method.

[source, java]
----
@EnableCaching
@SpringBootApplication
public class SimpleSpringbootAerospikeCacheApplication {
    public static void main(String[] args) {
        SpringApplication.run(SimpleSpringbootAerospikeCacheApplication.class, args);
    }
}
----

=== Test

We will use Postman to simulate client requests.

==== Add User (@CachePut)

a. Create a new POST request with the following url: http://localhost:8080/users

b. Add a new key-value header in the Headers section:

    Key: Content-Type

    Value: application/json

c. Add a Body in a valid JSON format:

    {
       "id":1,
       "name":"guthrie",
       "email":"guthriegovan@gmail.com",
       "age":35
    }

d. Press Send.

[source, text]
----
aql> select * from test
+-----+-----------+----------+-------------+-------------------------------------+
| @user_key  | name | @_class | email         | age                             |
+-----+-----------+----------+-------------+-------------------------------------+
| "1" | "guthrie" | "com.aerospike.cache.simplespringbootaerospikecache.objects.User"  | "guthriegovan@gmail.com" | 35 |
+-----+-----------+----------+-------------+-------------------------------------+
----

We can now see that this user was added to the cache.

==== Read User (@Cacheable)

a. Create a new GET request with the following url: http://localhost:8080/users/1

b. Add a new key-value header in the Headers section:

    Key: Content-Type

    Value: application/json

c. Press Send.

==== Remove User (@CacheEvict)

a. Create a new DELETE request with the following url: http://localhost:8080/users/1

b. Add a new key-value header in the Headers section:

    Key: Content-Type

    Value: application/json

c. Press Send.

We can now see that this user was deleted from the cache (thanks to the @CacheEvict annotation in the UserRepository).

[source, text]
----
aql> select * from test
+-----+-----------+----------+-------------+-------------------------------------+
0 rows in set
+-----+-----------+----------+-------------+-------------------------------------+
----

==== Cache miss (@Cacheable)

For reading `User` that is not in the cache we can use the GET request configured before with an id that
we know for sure is not there.

If we try calling the GET request with the id 5, we get the following user data:

    {
    "id": 5,
    "name": "jimmy page",
    "email": "jimmy@gmail.com",
    "age": 77
    }

We wrote it hard-coded in `UserRepository` to simulate an actual database fetch of a user id
that doesn't exist in the cache.

We can now also see that the user was added to the cache.

[source, text]
----
aql> select * from test
+-----+-----------+----------+-------------+-------------------------------------+
| @user_key  | name | @_class | email         | age                             |
+-----+-----------+----------+-------------+-------------------------------------+
| "1" | "jimmy page" | "com.aerospike.cache.simplespringbootaerospikecache.objects.User"  | "jimmy@gmail.com" | 77 |
+-----+-----------+----------+-------------+-------------------------------------+
----

