[[configuration]]
= Configuration

Configuration parameters can be set in a standard `application.properties` file using `spring-data-aerospike` prefix
or by overriding configuration from `AbstractAerospikeDataConfiguration` class.

[[configuration.application-properties]]
== Application.properties

Here is an example:

[source,properties]
----
# application.properties
spring-data-aerospike.hosts=localhost:3000
spring-data-aerospike.namespace=test
spring-data-aerospike.scans-enabled=false
spring-data-aerospike.send-key=true
spring-data-aerospike.create-indexes-on-startup=true
spring-data-aerospike.index-cache-refresh-seconds=3600
spring-data-aerospike.server-version-refresh-seconds=3600
spring-data-aerospike.query-max-records=10000
spring-data-aerospike.batch-write-size=100
spring-data-aerospike.keep-original-key-types=false
----

Configuration class:

[source, java]
----
@Configuration
@EnableAerospikeRepositories(basePackageClasses = { PersonRepository.class})
public class AerospikeConfiguration extends AbstractAerospikeDataConfiguration {

}
----

In this case extending `AbstractAerospikeDataConfiguration` class is required to enable repositories.

[[configuration.overriding-configuration]]
== Overriding configuration

Configuration can also be set by overriding `getHosts()` and `nameSpace()` methods as well as `AerospikeDataSettings` bean of the `AbstractAerospikeDataConfiguration` class.

Here is an example:

[source,java]
----
@EnableAerospikeRepositories(basePackageClasses = PersonRepository.class)
class ApplicationConfig extends AbstractAerospikeDataConfiguration {

    @Override
    protected Collection<Host> getHosts() {
        return Collections.singleton(new Host("localhost", 3000));
    }

    @Override
    protected String nameSpace() {
        return "test";
    }

    @Override
    @Bean
    public AerospikeDataSettings aerospikeDataSettings() {
        AerospikeDataSettings settings = new AerospikeDataSettings();
        settings.setCreateIndexesOnStartup(true);
        settings.setIndexCacheRefreshSeconds(3600);
        settings.setQueryMaxRecords(10000L);
        return settings;
    }
}
----

NOTE: `hosts` and `namespace` parameters set via application.properties have precedence over `getHosts()` and `nameSpace()` methods of the `AbstractAerospikeDataConfiguration` class.

[[configuration.parameters]]
== Configuration Parameters

[[configuration.hosts]]
=== hosts

[source,properties]
----
# application.properties
spring-data-aerospike.hosts=hostname1:3001, hostname2:tlsName2:3002
----

A String of hosts separated by `,` in form of `hostname1[:tlsName1][:port1],...`

IP addresses must be given in one of the following formats:

[source,text]
----
IPv4: xxx.xxx.xxx.xxx
IPv6: [xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx]
IPv6: [xxxx::xxxx]
----

IPv6 addresses must be enclosed by brackets. tlsName is optional.

*Default:* `null`.

[[configuration.namespace]]
=== namespace

[source,properties]
----
# application.properties
spring-data-aerospike.namespace=test
----

Aerospike DB namespace.

NOTE: `namespace` parameter set via application.properties has precedence over `nameSpace()` method of the `AbstractAerospikeDataConfiguration` class.

NOTE: To use multiple namespaces it is required to override `nameSpace()` and `AerospikeTemplate` for each
configuration class per namespace. In that case `spring-data-aerospike.namespace` parameter must be removed
from `application.properties`.
See https://github.com/aerospike-examples/spring-data-multiple-namespaces-example[multiple namespaces example]
for implementation details.

*Default:* `null`.

[[configuration.scans-enabled]]
=== scansEnabled

[source,properties]
----
spring-data-aerospike.scans-enabled=false
----

A scan can be an expensive operation as all records in the set must be read by the Aerospike server, and then the condition is applied to see if they match.

Due to the cost of performing this operation, scans from Spring Data Aerospike are disabled by default.

NOTE: Once this flag is enabled, scans run whenever needed with no warnings. This may or may not be optimal in a particular use case.

*Default:* `false`.

[[configuration.send-key]]
=== sendKey

[source,properties]
----
spring-data-aerospike.send-key=true
----

Send user defined key in addition to hash digest on both reads and writes. If the key is sent on write, it will be stored with the record on the server.

Default: `false` (do not send the user defined key).

[[configuration.create-indexes-on-startup]]
=== createIndexesOnStartup

[source,properties]
----
spring-data-aerospike.create-indexes-on-startup=true
----

Create secondary indexes specified using `@Indexed` annotation on startup.

*Default*: `true`.

[[configuration.index-cache-refresh-frequency-seconds]]
=== indexCacheRefreshSeconds

[source,properties]
----
spring-data-aerospike.index-cache-refresh-seconds=3600
----

Automatically refresh indexes cache every <N> seconds.

*Default*: `3600`.

[[configuration.server-version-refresh-frequency-seconds]]
=== serverVersionRefreshSeconds

[source,properties]
----
spring-data-aerospike.server-version-refresh-seconds=3600
----

Automatically refresh cached server version every <N> seconds.

*Default*: `3600`.

[[configuration.query-max-records]]
=== queryMaxRecords

[source,properties]
----
spring-data-aerospike.query-max-records=10000
----

Limit amount of results returned by server. Non-positive value means no limit.

*Default*: `10 000`.

[[configuration.batch-write-size]]
=== batchWriteSize

[source,properties]
----
spring-data-aerospike.batch-write-size=100
----

Maximum batch size for batch write operations. Non-positive value means no limit.

*Default*: `100`.

[[configuration.keep-original-key-types]]
=== keepOriginalKeyTypes

[source,properties]
----
spring-data-aerospike.keep-original-key-types=false
----

Define how `@Id` fields (primary keys) and `Map` keys are stored in the Aerospike database: `false` - always as `String`, `true` - preserve original type if supported.

[width="100%",cols="<20%,<30%,<30%",options="header",]
|===
|`@Id` field type |keepOriginalKeyTypes = `false` |keepOriginalKeyTypes = `true`
|`long` |`String` | `long`
|`int` |`String` | `long`
|`String` |`String` | `String`
|`byte[]` |`String` | `byte[]`
|other types |`String` | `String`
|===

NOTE: If `@Id` field's type cannot be persisted as is, it must be convertible to `String` and will be stored in the database as such, then converted back to the original type when the object is read. This is transparent to the application but needs to be considered if using external tools like `AQL` to view the data.

[width="100%",cols="<20%,<30%,<30%",options="header",]
|===
|`Map` key type |keepOriginalKeyTypes = `false` |keepOriginalKeyTypes = `true`
|`long` |`String` | `long`
|`int` |`String` | `long`
|`double` |`String` | `double`
|`String` |`String` | `String`
|`byte[]` |`String` | `byte[]`
|other types |`String` | `String`
|===

*Default*: `false` (store keys only as `String`).

