[[configuration]]
= Configuration

Configuration can be applied using one of these ways:

- Via parameters with `spring.aerospike*`
and `spring.data.aerospike*` prefixes in `application.properties` file, and using configuration class to enable repositories.

- By overriding methods `getHosts()`, `nameSpace()`, `configureDataSettings()` and enabling repositories
in a configuration class. These methods have precedence over parameters set in application.properties.

[[configuration.application-properties]]
== Application.properties and Enabling Repositories

Here is an example of this approach:

.application.properties
[source,properties]
----
# Aerospike
spring.aerospike.hosts=localhost:3000
spring.data.aerospike.namespace=test
spring.data.aerospike.scans-enabled=false
spring.data.aerospike.send-key=true
spring.data.aerospike.create-indexes-on-startup=true
spring.data.aerospike.index-cache-refresh-seconds=3600
spring.data.aerospike.server-version-refresh-seconds=3600
spring.data.aerospike.query-max-records=10000
spring.data.aerospike.batch-write-size=100
spring.data.aerospike.keep-original-key-types=false
----

.Configuration class
[source, java]
----
@Configuration
@EnableAerospikeRepositories(basePackageClasses = {TestRepository.class})
public class AerospikeConfiguration extends AbstractAerospikeDataConfiguration {

}
----

NOTE: Depending on the use case it might be required to override optional configuration methods like
xref:#aerospike.custom-converters[`customConverters()`] or xref:#configuration.client-policy[`getClientPolicy()`].

[[configuration.overriding-configuration]]
== Overriding Configuration Methods

Configuration can also be set by overriding `getHosts()`, `nameSpace()` and `configureDataSettings()` methods.

Here is an example:

[source,java]
----
@EnableAerospikeRepositories(basePackageClasses = TestRepository.class)
class ApplicationConfig extends AbstractAerospikeDataConfiguration {

    @Override
    protected Collection<Host> getHosts() {
        return Collections.singleton(new Host("localhost", 3000));
    }

    @Override
    protected String nameSpace() {
        return "test";
    }

    @Override
    protected void configureDataSettings(AerospikeDataSettings aerospikeDataSettings) {
        aerospikeDataSettings.setScansEnabled(false);
        aerospikeDataSettings.setCreateIndexesOnStartup(true);
        aerospikeDataSettings.setIndexCacheRefreshSeconds(3600);
        aerospikeDataSettings.setServerVersionRefreshSeconds(3600);
        aerospikeDataSettings.setQueryMaxRecords(10000L);
        aerospikeDataSettings.setBatchWriteSize(100);
        aerospikeDataSettings.setKeepOriginalKeyTypes(false);
    }
}
----

NOTE: Return values of `getHosts()`, `nameSpace()` and `configureDataSettings()` methods have precedence over the
parameters set via application.properties.

Depending on the use case it might be required to override other configuration methods like
xref:#aerospike.custom-converters[`customConverters()`] or xref:#configuration.client-policy[`getClientPolicy()`].


[[configuration.parameters]]
== Configuration Parameters

[[configuration.hosts]]
=== hosts

[source,properties]
----
# application.properties
spring.aerospike.hosts=hostname1:3001, hostname2:tlsName2:3002
----

A String of hosts separated by `,` in form of `hostname1[:tlsName1][:port1],...`

IP addresses must be given in one of the following formats:

[source,text]
----
IPv4: xxx.xxx.xxx.xxx
IPv6: [xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx]
IPv6: [xxxx::xxxx]
----

IPv6 addresses must be enclosed by brackets. tlsName is optional.

NOTE: Another way of defining hosts is overriding the `getHosts()` method.
It has precedence over `hosts` parameter from application.properties. Here is an example:

[source,java]
----
// overriding method
@EnableAerospikeRepositories(basePackageClasses = TestRepository.class)
class ApplicationConfig extends AbstractAerospikeDataConfiguration {

    @Override
    protected Collection<Host> getHosts() {
        return Collections.singleton(new Host("hostname1", 3001));
    }
}
----

*Default:* `null`.

[[configuration.namespace]]
=== namespace

[source,properties]
----
# application.properties
spring.data.aerospike.namespace=test
----

Aerospike DB namespace.

NOTE: Another way of defining hosts is overriding the `nameSpace()` method.
It has precedence over `namespace` parameter from application.properties.
Here is an example:

[source,java]
----
// overriding method
@EnableAerospikeRepositories(basePackageClasses = TestRepository.class)
class ApplicationConfig extends AbstractAerospikeDataConfiguration {

    @Override
    protected String nameSpace() {
        return "test";
    }
}
----

NOTE: To use multiple namespaces it is required to override `nameSpace()` and `AerospikeTemplate` for each
configuration class per namespace.
See https://github.com/aerospike-examples/spring-data-multiple-namespaces-example[multiple namespaces example]
for implementation details.

*Default:* `null`.

[[configuration.scans-enabled]]
=== scansEnabled

[source,properties]
----
# application.properties
spring.data.aerospike.scans-enabled=false
----

A scan can be an expensive operation as all records in the set must be read by the Aerospike server,
and then the condition is applied to see if they match.

Due to the cost of performing this operation, scans from Spring Data Aerospike are disabled by default.

NOTE: Another way of defining the parameter is overriding the `configureDataSettings()` method.
It has precedence over reading from application.properties. Here is an example:

[source,java]
----
// overriding method
@EnableAerospikeRepositories(basePackageClasses = TestRepository.class)
class ApplicationConfig extends AbstractAerospikeDataConfiguration {

    @Override
    protected void configureDataSettings(AerospikeDataSettings aerospikeDataSettings) {
        aerospikeDataSettings.setScansEnabled(false);
    }
}
----

NOTE: Once this flag is enabled, scans run whenever needed with no warnings. This may or may not be optimal
in a particular use case.

*Default:* `false`.

[[configuration.create-indexes-on-startup]]
=== createIndexesOnStartup

[source,properties]
----
# application.properties
spring.data.aerospike.create-indexes-on-startup=true
----

Create secondary indexes specified using `@Indexed` annotation on startup.

NOTE: Another way of defining the parameter is overriding the `configureDataSettings()` method.
It has precedence over reading from application.properties. Here is an example:

[source,java]
----
// overriding method
@EnableAerospikeRepositories(basePackageClasses = TestRepository.class)
class ApplicationConfig extends AbstractAerospikeDataConfiguration {

    @Override
    protected void configureDataSettings(AerospikeDataSettings aerospikeDataSettings) {
        aerospikeDataSettings.setCreateIndexesOnStartup(true);
    }
}
----

*Default*: `true`.

[[configuration.index-cache-refresh-frequency-seconds]]
=== indexCacheRefreshSeconds

[source,properties]
----
# application.properties
spring.data.aerospike.index-cache-refresh-seconds=3600
----

Automatically refresh indexes cache every <N> seconds.

NOTE: Another way of defining the parameter is overriding the `configureDataSettings()` method.
It has precedence over reading from application.properties. Here is an example:

[source,java]
----
// overriding method
@EnableAerospikeRepositories(basePackageClasses = TestRepository.class)
class ApplicationConfig extends AbstractAerospikeDataConfiguration {

    @Override
    protected void configureDataSettings(AerospikeDataSettings aerospikeDataSettings) {
        aerospikeDataSettings.setIndexCacheRefreshSeconds(3600);
    }
}
----

*Default*: `3600`.

[[configuration.server-version-refresh-frequency-seconds]]
=== serverVersionRefreshSeconds

[source,properties]
----
# application.properties
spring.data.aerospike.server-version-refresh-seconds=3600
----

Automatically refresh cached server version every <N> seconds.

NOTE: Another way of defining the parameter is overriding the `configureDataSettings()` method.
It has precedence over reading from application.properties. Here is an example:

[source,java]
----
// overriding method
@EnableAerospikeRepositories(basePackageClasses = TestRepository.class)
class ApplicationConfig extends AbstractAerospikeDataConfiguration {

    @Override
    protected void configureDataSettings(AerospikeDataSettings aerospikeDataSettings) {
        aerospikeDataSettings.setServerVersionRefreshSeconds(3600);
    }
}
----

*Default*: `3600`.

[[configuration.query-max-records]]
=== queryMaxRecords

[source,properties]
----
# application.properties
spring.data.aerospike.query-max-records=10000
----

Limit amount of results returned by server. Non-positive value means no limit.

NOTE: Another way of defining the parameter is overriding the `configureDataSettings()` method.
It has precedence over reading from application.properties. Here is an example:

[source,java]
----
// overriding method
@EnableAerospikeRepositories(basePackageClasses = TestRepository.class)
class ApplicationConfig extends AbstractAerospikeDataConfiguration {

    @Override
    protected void configureDataSettings(AerospikeDataSettings aerospikeDataSettings) {
        aerospikeDataSettings.setQueryMaxRecords(10000L);
    }
}
----

*Default*: `10 000`.

[[configuration.batch-write-size]]
=== batchWriteSize

[source,properties]
----
# application.properties
spring.data.aerospike.batch-write-size=100
----

Maximum batch size for batch write operations. Non-positive value means no limit.

NOTE: Another way of defining the parameter is overriding the `configureDataSettings()` method.
It has precedence over reading from application.properties. Here is an example:

[source,java]
----
// overriding method
@EnableAerospikeRepositories(basePackageClasses = TestRepository.class)
class ApplicationConfig extends AbstractAerospikeDataConfiguration {

    @Override
    protected void configureDataSettings(AerospikeDataSettings aerospikeDataSettings) {
        aerospikeDataSettings.setBatchWriteSize(100);
    }
}
----

*Default*: `100`.

[[configuration.keep-original-key-types]]
=== keepOriginalKeyTypes

[source,properties]
----
# application.properties
spring.data.aerospike.keep-original-key-types=false
----

Define how `@Id` fields (primary keys) and `Map` keys are stored in the Aerospike database:
`false` - always as `String`, `true` - preserve original type if supported.

[width="100%",cols="<20%,<30%,<30%",options="header",]
|===
|`@Id` field type |keepOriginalKeyTypes = `false` |keepOriginalKeyTypes = `true`
|`long` |`String` | `long`
|`int` |`String` | `long`
|`String` |`String` | `String`
|`byte[]` |`String` | `byte[]`
|other types |`String` | `String`
|===

NOTE: If `@Id` field's type cannot be persisted as is, it must be convertible to `String` and will be stored
in the database as such, then converted back to the original type when the object is read.
This is transparent to the application but needs to be considered if using external tools like `AQL` to view the data.

[width="100%",cols="<20%,<30%,<30%",options="header",]
|===
|`Map` key type |keepOriginalKeyTypes = `false` |keepOriginalKeyTypes = `true`
|`long` |`String` | `long`
|`int` |`String` | `long`
|`double` |`String` | `double`
|`String` |`String` | `String`
|`byte[]` |`String` | `byte[]`
|other types |`String` | `String`
|===

NOTE: Another way of defining the parameter is overriding the `configureDataSettings()` method.
It has precedence over reading from application.properties. Here is an example:

[source,java]
----
// overriding method
@EnableAerospikeRepositories(basePackageClasses = TestRepository.class)
class ApplicationConfig extends AbstractAerospikeDataConfiguration {

    @Override
    protected void configureDataSettings(AerospikeDataSettings aerospikeDataSettings) {
        aerospikeDataSettings.setKeepOriginalKeyTypes(false);
    }
}
----

*Default*: `false` (store keys only as `String`).

[[configuration.write-sorted-maps]]
=== writeSortedMaps

[source,properties]
----
# application.properties
spring.data.aerospike.writeSortedMaps=true
----

Define how Maps and POJOs are written: `true` - as sorted maps (`TreeMap`, default), `false` - as unsorted (`HashMap`).

Writing as unsorted maps (`false`) degrades performance of Map-related operations and does not allow comparing Maps,
so it is strongly recommended to change the default value only if required during upgrade from older versions
of Spring Data Aerospike.

NOTE: Another way of defining the parameter is overriding the `configureDataSettings()` method.
It has precedence over reading from application.properties. Here is an example:

[source,java]
----
// overriding method
@EnableAerospikeRepositories(basePackageClasses = TestRepository.class)
class ApplicationConfig extends AbstractAerospikeDataConfiguration {

    @Override
    protected void configureDataSettings(AerospikeDataSettings aerospikeDataSettings) {
        aerospikeDataSettings.setWriteSortedMaps(true);
    }
}
----

*Default*: `true` (write Maps and POJOs as sorted maps).

[[configuration.client-policy]]
== ClientPolicy

To set the necessary `ClientPolicy` parameters of the underlying Java client, override the `getClientPolicy()` method and call `super.getClientPolicy()` to apply default values first.

Here is an example with several parameters set for running a test:

[source,java]
----
public class MyConfiguration extends AbstractAerospikeDataConfiguration {

    @Override
    protected ClientPolicy getClientPolicy() {
        ClientPolicy clientPolicy = super.getClientPolicy(); // applying default values first
        int totalTimeout = 2000;
        clientPolicy.readPolicyDefault.totalTimeout = totalTimeout;
        clientPolicy.writePolicyDefault.totalTimeout = totalTimeout;
        clientPolicy.batchPolicyDefault.totalTimeout = totalTimeout;
        clientPolicy.infoPolicyDefault.timeout = totalTimeout;
        clientPolicy.readPolicyDefault.maxRetries = 3;
        return clientPolicy;
    }
}
----

