[[configuration]]
= Configuration

Configuration can be accessed via standard `application.properties`.
Here is an example:

[source,properties]
----
spring-data-aerospike.hosts=localhost:3000
spring-data-aerospike.namespace=TEST
----

[[configuration.parameters]]
== Configuration Parameters

[[configuration.scans-enabled]]
=== scansEnabled

A scan can be an expensive operation as all records in the set must be read by the Aerospike server, and then the condition is applied to see if they match.

Due to the cost of performing this operation, scans from Spring Data Aerospike are disabled by default.

NOTE: Once this flag is enabled, scans run whenever needed with no warnings. This may or may not be optimal in a particular use case.

*Default:* `false`.

[[configuration.send-key]]
=== sendKey

Send user defined key in addition to hash digest on both reads and writes. If the key is sent on write, it will be stored with the record on the server.

Default: `false` (do not send the user defined key).

[[configuration.create-indexes-on-startup]]
=== createIndexesOnStartup

Create secondary indexes specified using `@Indexed` annotation on startup.

*Default*: `true`.

[[configuration.index-cache-refresh-frequency-seconds]]
=== indexCacheRefreshSeconds

Automatically refresh indexes cache every <N> seconds.

*Default*: `3600`.

[[configuration.server-version-refresh-frequency-seconds]]
=== serverVersionRefreshSeconds

Automatically refresh cached server version every <N> seconds.

*Default*: `3600`.

[[configuration.query-max-records]]
=== queryMaxRecords

Limit amount of results returned by server. Non-positive value means no limit.

*Default*: `10 000`.

[[configuration.batch-write-size]]
=== batchWriteSize

Maximum batch size for batch write operations. Non-positive value means no limit.

*Default*: `100`.

[[configuration.keep-original-key-types]]
=== keepOriginalKeyTypes

Define how `@Id` fields (primary keys) and `Map` keys are stored in the Aerospike database: `false` - always as `String`, `true` - preserve original type if supported.

[width="100%",cols="<20%,<30%,<30%",options="header",]
|===
|`@Id` field type |keepOriginalKeyTypes = `false` |keepOriginalKeyTypes = `true`
|`long` |`String` | `long`
|`int` |`String` | `long`
|`String` |`String` | `String`
|`byte[]` |`String` | `byte[]`
|other types |`String` | `String`
|===

NOTE: If `@Id` field's type cannot be persisted as is, it must be convertible to `String` and will be stored in the database as such, then converted back to the original type when the object is read. This is transparent to the application but needs to be considered if using external tools like `AQL` to view the data.

[width="100%",cols="<20%,<30%,<30%",options="header",]
|===
|`Map` key type |keepOriginalKeyTypes = `false` |keepOriginalKeyTypes = `true`
|`long` |`String` | `long`
|`int` |`String` | `long`
|`double` |`String` | `double`
|`String` |`String` | `String`
|`byte[]` |`String` | `byte[]`
|other types |`String` | `String`
|===

*Default*: `false` (store keys only as `String`).

