[[custom-queries]]
= Custom Queries

[[custom-queries-intro]]
== Introduction

<<aerospike.derived-query,Derived queries>> are helpful for most querying tasks. Each repository adds more
functionality by providing query methods.

There are some cases, however, when data finding tasks require building query methods which are more complex,
more flexible or unsupported in a standard repository. <<aerospike.custom-query,Custom queries>> are such a special
mechanism in Spring Data Aerospike. Currently only finding (reading) queries are supported.

[[find-using-query]]
== Find Using Query

Users can perform a custom query by passing a `Query` with a custom `Qualifier` to `findUsingQuery(Query)`.
The qualifier may contain other qualifiers and combine them into conjunctions with `Qualifier.and(...)` or
disjunctions with `Qualifier.or(...)`, with some limitations due to qualifier type.

Custom `Qualifier` can be created for queries of the following types: regular (Aerospike bins), metadata,
DSL expression, indexed with expression, ids (primary keys) and filtering (accepting `Expression`
and/or secondary index `Filter` for additional flexibility, manual handling or when working with legacy code).
Below are examples for the mentioned custom queries types.

[[custom-query-regular]]
== Regular Custom Query Example

[source,java]
----
include::{examples-java}/org/springframework/data/aerospike/examples/blocking/customquery/types/CustomQueryTypesExample.java[tag=custom-query-regular-qualifier,indent=0]
----

[[custom-query-id]]
== ID Custom Query Example

[source,java]
----
include::{examples-java}/org/springframework/data/aerospike/examples/blocking/customquery/types/CustomQueryTypesExample.java[tag=custom-query-id-qualifier,indent=0]

----

[[custom-query-id-and-regular]]
== ID and Regular Custom Query Example

[source,java]
----
include::{examples-java}/org/springframework/data/aerospike/examples/blocking/customquery/types/CustomQueryTypesExample.java[tag=custom-query-id-and-regular-qualifier,indent=0]

----

[[custom-query-metadata]]
== Metadata Custom Query Example

[source,java]
----
include::{examples-java}/org/springframework/data/aerospike/examples/blocking/customquery/types/CustomQueryTypesExample.java[tag=custom-query-metadata-qualifier,indent=0]

----

[[custom-query-dsl-expression]]
== DSL expression Custom Query Example

[source,java]
----
include::{examples-java}/org/springframework/data/aerospike/examples/blocking/customquery/types/CustomQueryTypesExample.java[tag=custom-query-dsl-expression-qualifier,indent=0]

----

[[custom-query-indexed-expression]]
== Indexed Using Expression Custom Query Example

NOTE: Expression indexes require Aerospike Server 8.1.0 or later. The runnable example skips this section on older
server versions.

[source,java]
----
include::{examples-java}/org/springframework/data/aerospike/examples/blocking/customquery/types/CustomQueryTypesExample.java[tag=custom-query-indexed-expression-qualifier,indent=0]
----


[[custom-query-filtering]]
== Filtering Custom Query Example

[source,java]
----
include::{examples-java}/org/springframework/data/aerospike/examples/blocking/customquery/types/CustomQueryTypesExample.java[tag=custom-query-filtering-qualifier,indent=0]
----

