== Installation & Usage

=== Getting Started

To use Spring Data Aerospike in your project, the first step is to add it to your build process. For Maven, this is as simple as:

[source, xml]
----
<dependency>
    <groupId>com.aerospike</groupId>
    <artifactId>spring-data-aerospike</artifactId>
    <version>4.2.0</version>
</dependency>
----

For Gradle:

[source, text]
----
implementation group: 'com.aerospike', name: 'spring-data-aerospike', version: '4.2.0'
----

=== Connecting to Aerospike DB

Connecting to the repository is easy with the help of the `AbstractAerospikeDataConfiguration` class.

[source, java]
----
@Configuration
@EnableAerospikeRepositories(basePackageClasses = { PersonRepository.class})
public class AerospikeConfiguration extends AbstractAerospikeDataConfiguration {
    @Override
    protected Collection<Host> getHosts() {
        return Collections.singleton(new Host("localhost", 3000));
    }

    @Override
    protected String nameSpace() {
        return "test";
    }
}
----

`@Configuration` tells Spring that this class contains configuration data, and `@EnableAerospikeRepositories` activates Aerospike repositories that can be used for data access. The parameter to this annotation tells Spring Data Aerospike where to look for the repositories. This can be a list of package names as strings using the `basePackages` value, or a list of classes through the `basePackageClass` value. If the latter is used (as in this example), the class is used to determine which package to scan, and all repositories in that package will be available for use. More details on repositories are below.

The `AbstractAerospikeDataConfiguration` class exposes a number of beans which Spring Data Aerospike uses internally. Some of these, in particular the `AerospikeTemplate` bean, are useful in their own right if finer grained control over data access is needed. The primary information required by this configuration is how to connect to the cluster, provided through the `getHosts` and `nameSpace` calls.

=== Creating Functionality

The base functionality for using Spring Data is provided by the AerospikeRepository interface. This typically takes 2 parameters:

[arabic]
. The type which this class manages, typically an entity class to be stored in the database.
. The type of the ID for this class.

Application code typically extends this interface for each of the types to be managed, and methods can be added to the interface to determine how the application can access the data. For example, consider a class `Person` with a simple structure:

[source, java]
----
@AllArgsConstructor
@NoArgsConstructor
@Data
@Document
public class Person {
    @Id
    private long id;
    private String firstName;
    private String lastName;
    @Field("dob")
    private Date dateOfBirth;
}
----

Note that this example uses the https://projectlombok.org/[Project Lombok] annotations to remove the need for explicit constructors and getters and setters. Normal POJOs which define these on their own can ignore the `@AllArgsConstructor`, `@NoArgsConstructor` and `@Data` annotations. The `@Document` annotation tells Spring Data Aerospike that this is a domain object to be persisted to the database, and `@Id` identifies the primary key of this class. The `@Field` annotation is used to create a shorter name for the bin in the Aerospike database (`dateOfBirth` will be stored in a bin called `dob` in this example).

For the `Person` object to be persisted to Aerospike, you must create an interface with the desired methods for retrieving data. For example:

[source, java]
----
public interface PersonRepository extends AerospikeRepository<Person, Long> {
    public List<Person> findByLastName(String lastName);
}
----

This defines a repository which can write `Person` entities as well as being able to query people by last name. The `AerospikeRepository` extends both `PagingAndSortingRepository` and `CrudRepository` so methods like `count()`, `findById()`, `save()` and `delete()` are there by default. For reactive users, use the `ReactiveAerospikeRepository` instead.

Note that this is just an interface and not an actual class. In the background, when your context gets initialized, actual implementations for your repository descriptions get created and you can access them through regular beans. This means you will save lots of boilerplate code while still exposing full CRUD semantics to your service layer and application.

Once this is defined, the repository is ready for use. A sample Spring Controller which uses this repository could be:

[source, java]
----
@RestController
public class ApplicationController {
    @Autowired
    private PersonRepository personRepsitory;

    @GetMapping("/seed")
    public int seedData() {
        Person person = new Person(1, "Bob", "Jones", new GregorianCalendar(1971, 12, 19).getTime());
        personRepsitory.save(person);
        return 1;
    }

    @GetMapping("/findByLastName/{lastName}")
    public List<Person> findByLastName(@PathVariable(name = "lastName", required=true) String lastName) {
        return personRepsitory.findByLastName(lastName);
    }
}
----

Invoking the `seed` method above gives you a record in the Aerospike database which looks like:

[source, text]
----
aql> select * from test.Person where pk = "1"
+-----+-----------+----------+-------------+-------------------------------------+
| PK  | firstName | lastName | dob         | @_class                             |
+-----+-----------+----------+-------------+-------------------------------------+
| "1" | "Bob"     | "Jones"  | 64652400000 | "com.aerospike.sample.model.Person" |
+-----+-----------+----------+-------------+-------------------------------------+
1 row in set (0.001 secs)
----

There are 2 important things to notice here:

[arabic]
. The fully qualified path of the class is listed in each record. This is needed to instantiate the class correctly, especially in cases where the compile-time type and runtime type of the object differ. For example, where a field is declared as a super class but the instantiated class is a sub-class.
. The `long` id field was turned into a `String` when stored in the database. All `@Id` fields must be convertible to `String` and will be stored in the database as such, then converted back to the original type when the object is read. This is transparent to the application, but needs to be considered if using an external tool like `AQL` to view the data.