[[indexed-annotation]]
= Indexed Annotation

The `@Indexed` annotation allows to create secondary index on a specific field of a Java object.
For the details on secondary indexes in Aerospike see <<secondary-indexes, Secondary Indexes>>.

The annotation allows to specify the following parameters:

[width="100%",cols="<14%,<24%,<18%,<26%",options="header",]
|===
|parameter      |index type                             |mandatory |example
|name           |index name                             |yes |"friend_address_keys_idx"
|type           |index type                             |yes |IndexType.STRING
|bin            |indexed bin type                       |no  |"friend"
|collectionType |index type                             |no  |IndexCollectionType.MAPKEYS
|ctx            |context (path to the indexed elements) |no  |"address"
|===

Here is an example of creating a complex secondary index for fields of a person's friend address.

[source,java]
----
@AllArgsConstructor
@NoArgsConstructor
@Setter
@Data
@Document
public class Person {

    @Id
    String id;
    Friend friend;
}

@NoArgsConstructor
@Setter
@Data
public class Friend {

    @Indexed(type = IndexType.STRING, name = "friend_address_keys_idx", bin = "friend",
    collectionType = IndexCollectionType.MAPKEYS, ctx = "address")
    Address address;
}

@Data
@AllArgsConstructor
public class Address {

    private String street;
    private Integer apartment;
    private String zipCode;
    private String city;
}

@Test
void test() {
    Friend carter = new Friend();
    carter.setAddress("Street", 14, "1234567890", "City");
    repository.save(carter);

    Person dave = new Person();
    dave.setFriend(carter);
    repository.save(dave);
}
----

A `Person` object in this example has a field called "friend" (`Friend` object).
A `Friend` object has a field called "address" (`Address` object).
So when "friend" field is set to a `Friend` with existing `Address`, we have a person with a friend who has
a particular address (`dave` in the example above).

`Address` object on its own has certain fields: `street`, `apartment`, `zipCode`, `city`.

NOTE: In Aerospike DB a POJO (such as `Address`) is represented by a Map, so the fields of POJO become map keys.

Thus, we set `collectionType` to `IndexCollectionType.MAPKEYS`.

`Ctx` parameter represents context, or path to the necessary element in the specified bin ("friend") - which is "address", because we want to index by fields of friend's address.

== Secondary Index Context DSL

Secondary index context (`ctx` parameter in `@Indexed` annotation) represents path to a necessary element in hierarchy. It uses infix notation.

The document path is described as dot-separated context elements (e.g., "a.b.[2].c") written as a string. A path is made of singular path elements and ends with one (a leaf element) or more elements (leaves) - for example, "a.b.[2].c.[0:3]".

[width="100%",cols="<14%,<24%,<18%",options="header",]
|===
|Path Element      |Matches                             |Notes
|`"a"`               |Map key “a”                         |Single element by key
|`"1"` or `'1'`        |Map key (numeric string) “1”        |
|`1`                 |Map key (integer) 1                 |
|`\{1\}`             |Map index 1                         |
|`{=1}`              |Map value (integer) 1               |
|`{=bb}`             |Map value “bb”                      |Also {="bb"}
|`{="1"}` or `{='1'}`  |Map value (string) “1”              |
|`{#1}`              |Map rank 1                          |
|`[1]`               |List index 1                        |
|`[=1]`              |List value 1                        |
|`[#1]`             |List rank 1                         |
|===

=== Example

Let's consider a Map bin example:

[source,text]
----
{
  1: a,
  2: b,
  4: d,
  "5": e,
  a: {
    55: ee,
    "66": ff,
    aa: {
      aaa: 111,
      bbb: 222,
      ccc: 333,
    },
    bb: {
      bba: 221,
      bbc: 223
    },
    cc: [ 22, 33, 44, 55, 43, 32, 44 ],
    dd: [ {e: 5, f:6}, {z:26, y:25}, {8: h, "9": j} ]
  }
}
----

So the following will be true:

[width="100%",cols="<24%,<30%,<18%",options="header",]
|===
|Path              |CTX                                                    |Matched Value
|a.aa.aaa          |[mapKey("a"), mapKey("aa"), mapKey("aaa")]             |111
|a.55              |[mapKey("a"), mapKey(55)]                              |ee
|a."66"            |[mapKey("a"), mapKey("66")]                            |ff
|a.aa.\{2\}        |[mapKey("a"), mapKey("aa"),mapIndex(2)]                |333
|a.aa.{=222}       |[mapKey("a"), mapKey("aa"),mapValue(222)]              |222
|a.bb.{#-1}        |[mapKey("a"), mapKey("bb"),mapRank(-1)]                |223
|a.cc.[0]          |[mapKey("a"), mapKey("cc"),listIndex(0)]               |22
|a.cc.[#1]         |[mapKey("a"), mapKey("cc"),listRank(1)]                |32
|a.cc.[=44]        |[mapKey("a"), mapKey("cc"),listValue(44)]              |[44, 44]
|a.dd.[0].e        |[mapKey("a"), mapKey("dd"),listIndex(0), mapKey("e")]  |5
|a.dd.[2].8        |[mapKey("a"), mapKey("dd"),listIndex(2), mapKey(8)]    |h
|a.dd.[-1]."9"     |[mapKey("a"), mapKey("dd"),listIndex(-1), mapKey("9")] |j
|a.dd.[1].{#0}     |[mapKey("a"), mapKey("dd"),listIndex(1), mapRank(0)]   |y
|===

