[[aerospike.query_methods.collection]]
= Collection Repository Queries

NOTE: *Collection repository queries* utilize `query()` operation of the underlying Java client.

[width="100%",cols="<7%,<30%,<25%,<10%,<20%",options="header",]
|===
|Keyword |Repository query sample |Snippet |Uses secondary index |Notes

|Is, Equals

or no keyword a|
[source,java]
----
findByStringList(Collection<String> stringList)
----
|...where x.stringList = ?
|only scan
|

|Not, IsNot a|
[source,java]
----
findByStringListNot(Collection<String> stringList)
----
|...where x.stringList <> ?
|only scan
|

|In a|
[source,java]
----
findByStringListIn(Collection<Collection<String>>)
----
|...where x.stringList in ?
|only scan
|Find records where `stringList` bin value equals one of the collections in the given argument.

|Not In a|
[source,java]
----
findByStringListNotIn(Collection<Collection<String>>)
----
|...where x.stringList not in ?
|only scan
|Find records where `stringList` bin value is not equal to any of the collections in the given argument.

|Null, IsNull a|
[source,java]
----
findByStringListIsNull()
----
|...where x.stringList = null or x.stringList does not exist
|only scan
|The same as "does not exist", objects and fields exist in AerospikeDB when their value is not equal to null.

|Exists

NotNull, IsNotNull a|
[source,java]
----
findByStringListExists()
----

[source,java]
----
findByStringListNotNull()
----

|...where x.stringList != null
|only scan
|("Exists" and "IsNotNull" represent the same functionality and can be used interchangeably, objects and fields
exist in AerospikeDB when their value is not equal to null).

|LessThan, IsLessThan a|
[source,java]
----
findByStringListLessThan(Collection<String> stringList)
----
|...where x.stringList < ?
|only scan
|Find records where `stringList` bin value has fewer elements or has a corresponding element lower in ordering
than in the given argument.
See https://docs.aerospike.com/server/guide/data-types/cdt-ordering#list[information about ordering].

|LessThanEqual, IsLessThanEqual a|
[source,java]
----
findByStringListLessThanEqual(Collection<String> stringList)
----
|...where x.stringList < = ?
|only scan
|Find records where `stringList` bin value has smaller or the same amount of elements or has each
corresponding element lower in ordering or the same as in the given argument.
See https://docs.aerospike.com/server/guide/data-types/cdt-ordering#list[information about ordering].

|GreaterThan, IsGreaterThan a|
[source,java]
----
findByStringListGreaterThan(Collection<String> stringList)
----
|...where x.stringList > ?
|only scan
|Find records where `stringList` bin value has more elements or has a corresponding element higher in ordering
than in the given argument.
See https://docs.aerospike.com/server/guide/data-types/cdt-ordering#list[information about ordering].

|GreaterThanEqual, IsGreaterThanEqual a|
[source,java]
----
findByStringListGreaterThanEqual(Collection<String> stringList)
----
|...where x.stringList >= ?
|only scan
|Find records where `stringList` bin value has larger or the same amount of elements or has each
corresponding element higher in ordering or the same as in the given argument.
See https://docs.aerospike.com/server/guide/data-types/cdt-ordering#list[information about ordering].

|Between, IsBetween a|
[source,java]
----
findByStringListBetween(Collection<String> lowerLimit, Collection<String> upperLimit)
----
|...where x.stringList between ? and ?
|only scan
|Find records where `stringList` bin value is in the range between the given arguments.
See https://docs.aerospike.com/server/guide/data-types/cdt-ordering#list[information about ordering].

|Containing, IsContaining, Contains a|
[source,java]
----
findByStringListContaining(String string)
----
|...where x.stringList contains ?
|only scan
|

|NotContaining, IsNotContaining, NotContains a|
[source,java]
----
findByStringListNotContaining(String string)
----
|...where x.stringList not contains ?
|only scan
|

|And a|
[source,java]
----
findByStringListAndIntList(QueryParam stringList, QueryParam intList)
----
|...where x.stringList = ? and x.intList = ?
|only scan
|

|Or a|
[source,java]
----
findByStringListOrIntList(QueryParam stringList, QueryParam intList)
----
|...where x.stringList = ? or x.intList = ?
|only scan
|
|===
