[[aerospike.query-methods-combined]]
= Combined Derived Queries

In Spring Data, combined derived queries use method-name connectors such as `And` and `Or` to combine multiple
conditions. `And` forms a conjunction, `Or` forms a disjunction, and both are created from repository method names.
For the broader definition across derived, declared, and custom query styles, see <<aerospike.combined-query>>.

For more details,
see link:https://docs.spring.io/spring-data/commons/reference/repositories/query-methods-details.html[Defining Query Methods].

For instance, a method like `findByFirstNameAndLastName` will fetch records matching both conditions,
while `findByFirstNameOrLastName` will return records that match either condition. These query methods simplify
database interaction by reducing boilerplate code and relying on convention over configuration for readability
and maintainability.

In Spring Data Aerospike you define such queries by adding query method signatures to a `Repository`, as you would
typically, wrapping each query parameter with `QueryParam.of()` method. This method is required to pass arguments
to each part of a combined query, it can receive one or more objects of the same type.

This way `QueryParam` stores arguments passed to each part of a combined repository query, e.g.,
`repository.findByNameAndEmail(QueryParam.of("John"), QueryParam.of("email"))`.

Here are some examples:


[source,java]
----
include::{examples-java}/org/springframework/data/aerospike/examples/combined/blocking/derived/repository/BlockingDerivedQueryRepository.java[tag=combined-derived-query-repository]
----

.Conjunctions can use an eligible secondary index
[source,java]
----
include::{examples-java}/org/springframework/data/aerospike/examples/combined/blocking/derived/BlockingDerivedQueryConjunctionExample.java[tag=combined-derived-query-conjunction-usage,indent=0]
----

.Disjunctions are scan-backed
[source,java]
----
include::{examples-java}/org/springframework/data/aerospike/examples/combined/blocking/derived/BlockingDerivedQueryDisjunctionExample.java[tag=combined-derived-query-disjunction-usage,indent=0]
----

.No-index contexts require scans
[source,java]
----
include::{examples-java}/org/springframework/data/aerospike/examples/combined/blocking/derived/BlockingDerivedQueryNoIndexExample.java[tag=combined-derived-query-no-index-usage,indent=0]
----

== Combined Queries and Secondary Index

There are certain rules applied to processing such queries regarding secondary index in Spring Data Aerospike:

* If no query parts correspond to a secondary index, a <<aerospike.scan-operation, scan operation>> is used
* If only one part of a query has a corresponding secondary index eligible for use, that index will be used. For instance, if an index was created for the `name` String bin, then it will be used in queries like `findByNameAndJob()`, `findByNameAndJobAndEmail()`, `findByJobAndName()` etc.
* If two or more query parts have corresponding secondary indexes eligible for use, one index will be chosen based on cardinality.

=== Secondary Indexes Cardinality

Cardinality is calculated the following way: when indexes info is retrieved (configurable, typically on startup and then once an hour), Spring Data Aerospike uses `sindex-stat` command to gather statistics for secondary indexes to look at the ratio of entries to unique bin values for a given secondary index on the node (`entries_per_bval`), which is used as cardinality based on distribution of data within the secondary index.

So when a query has more than one SI, cardinality of each query part (qualifier) is compared using cache of indexes, and the index with the lowest ratio of entries to unique bin values is selected. If two or more parts have the same cardinality, the first of them will be used.

