[[aerospike.query-methods-combined]]
= Combined Query Methods

In Spring Data, complex query methods using `And` or `Or` conjunction allow developers to define custom
database queries based on method names that combine multiple conditions. These methods leverage query derivation,
enabling developers to create expressive and type-safe queries by simply defining method signatures.

For more details,
see link:https://docs.spring.io/spring-data/commons/reference/repositories/query-methods-details.html[Defining Query Methods].

For instance, a method like `findByFirstNameAndLastName` will fetch records matching both conditions,
while `findByFirstNameOrLastName` will return records that match either condition. These query methods simplify
database interaction by reducing boilerplate code and relying on convention over configuration for readability
and maintainability.

In Spring Data Aerospike you define such queries by adding query methods signatures to a `Repository`, as you would
typically, wrapping each query parameter with `QueryParam.of()` method. This method is required to pass arguments
to each part of a combined query, it can receive one or more objects of the same type.

This way `QueryParam` stores arguments passed to each part of a combined repository query, e.g.,
`repository.findByNameAndEmail(QueryParam.of("John"), QueryParam.of("email"))`.

Here are some examples:


[source,java]
----
public interface CustomerRepository extends AerospikeRepository<Customer, String> {

     // simple query
    List<Customer> findByLastName(String lastName);

     // simple query
    List<Customer> findByFirstName(String firstName);

    // combined query with AND conjunction
    List<Customer> findByEmailAndFirstName(QueryParam email, QueryParam firstName);

    // combined query with AND conjunctions
    List<Customer> findByIdAndFirstNameAndAge(QueryParam id, QueryParam firstName, QueryParam age);

    // combined query with OR conjunction
    List<Consumer> findByFirstNameOrAge(QueryParam firstName, QueryParam age);

    // combined query with AND and OR conjunctions
    List<Consumer> findByEmailAndFirstNameOrAge(QueryParam email, QueryParam firstName, QueryParam age);
}

    @Test
    void findByCombinedQuery() {
        QueryParam email = QueryParam.of(dave.getEmail());
        QueryParam name = QueryParam.of(carter.getFirstName());
        List<Customer> customers = repository.findByEmailAndFirstName(email, name);
        assertThat(customers).isEmpty();

        QueryParam ids = QueryParam.of(List.of(leroi.getId(), dave.getId(), carter.getId()));
        QueryParam firstName = QueryParam.of(leroi.getFirstName());
        QueryParam age = QueryParam.of(leroi.getAge());
        List<Customer> customers2 = repository.findByIdAndFirstNameAndAge(ids, firstName, age);
        assertThat(customers).containsOnly(leroi);
    }
----

== Combined Queries and Secondary Index

There are certain rules applied to processing such queries regarding secondary index in Spring Data Aerospike:

* If no query parts correspond to a secondary index, a <<aerospike.scan-operation, scan operation>> is used
* If only one part of a query has a corresponding secondary index eligible for use, that index will be used. For instance, if an index was created for the `name` String bin, then it will be used in queries like `findByNameAndJob()`, `findByNameAndJobAndEmail()`, `findByJobAndName()` etc.
* If two or more query parts have corresponding secondary indexes eligible for use, one index will be chosen based on cardinality.

=== Secondary Indexes Cardinality

Cardinality is calculated the following way: when indexes info is retrieved (configurable, typically on startup and then once an hour), Spring Data Aerospike uses `sindex-stat` command to gather statistics for secondary indexes to look at the ratio of entries to unique bin values for a given secondary index on the node (`entries_per_bval`), which is used as cardinality based on distribution of data within the secondary index.

So when a query has more than one SI, cardinality of each query part (qualifier) is compared using cache of indexes, and the index with the lowest ratio of entries to unique bin values is selected. If two or more parts have the same cardinality, the first of them will be used.

