[[aerospike.query-methods-preface]]
= Query Methods

Spring Data Aerospike supports defining queries by method names in the Repository interface so that the implementation
is generated.
The format of method names is fairly flexible, comprising a verb and criteria.

Some of the verbs include `find`, `query`, `read`, `get`, `count` and `delete`.
For example, queries might look like `findByFirstName`, `countByLastName` etc.

For more details, refer to basic Spring Data documentation:
link:https://docs.spring.io/spring-data/rest/reference/data-commons/repositories/query-methods-details.html[Defining Query Methods].

== Using Secondary Index

Repository queries in Spring Data Aerospike can be divided into 3 groups:

* Queries that utilize secondary index (if at least one corresponding index is available)

* Queries that only use <<aerospike.scan-operation, scan operation>>

* Queries that use both secondary index and scan (e.g., for indexed queries combined with AND
or when looking for a nested integer or string property).

If no corresponding secondary index is found, each query does a fallback to using scan only.

For details on particular repository queries see the tables referring to queries examples below.

== Repository Query Keywords

Here are the references to the examples of repository queries:

<<aerospike.query_methods.simple_property, Simple property queries>>

<<aerospike.query_methods.collection, Collection queries>>

<<aerospike.query_methods.map, Map queries>>

<<aerospike.query_methods.pojo, POJO queries>>

<<aerospike.query_methods.id, Id queries>>

NOTE: *Repository read queries featuring id equality* (e.g., `findById()`, `findByIds()`, `findByFirstNameAndId()`, `findAllById()`,
`countById()`, `existsById()` etc.) utilize `get()` operation of the underlying Java client.
*Repository read queries without id or with 'string id like'* (e.g., `findByFirstName()`, `findByFirstNameAndLastName()`, `findAll()` , `findByIdLike()` etc.)
utilize `query()` operation of the underlying Java client.


== Repository Interface Example

Below is an example of an interface with several query methods:

[source,java]
----
public interface PersonRepository extends AerospikeRepository<Person, Long> {
    List<Person> findByLastName(String lastName);
    List<Person> findByLastNameContaining(String lastName);
    List<Person> findByLastNameStartingWith(String lastName);
    List<Person> findByLastNameAndFirstNameContaining(String lastName, String firstName);
    List<Person> findByAgeBetween(long startAge, long endAge);
    Optional<Person> findById(Long id);
}
----
