[[aerospike.query_methods.pojo]]
= POJO Repository Queries

NOTE: *These repository queries* utilize `query()` operation of the underlying Java client.

[width="100%",cols="<7%,<30%,<25%,<10%,<20%",options="header",]
|===
|Keyword |Repository query sample |Snippet |Uses secondary index |Notes

|Is, Equals

or no keyword a|
[source,java]
----
findByAddress(Address address)
----
|...where x.address = ?
|only scan
|

|Not, IsNot a|
[source,java]
----
findByAddressNot(Address address)
----
|...where x.address <> ?
|only scan
|

|In a|
[source,java]
----
findByAddressIn(Collection<Address>)
----
|...where x.address in ?
|only scan
|Find records where `address` bin value equals one of the Address objects in the given argument.

|Not In a|
[source,java]
----
findByAddressNotIn(Collection<Address>)
----
|...where x.address not in ?
|only scan
|Find records where `address` bin value is not equal to any of the Address objects in the given argument.

|Null, IsNull a|
[source,java]
----
findByAddressIsNull()
----
|...where x.address = null or x.address does not exist
|only scan
|The same as "does not exist", objects and fields exist in AerospikeDB when their value is not equal to null.

|Exists

NotNull, IsNotNull a|
[source,java]
----
findByAddressExists()
----

[source,java]
----
findByAddressNotNull()
----
|...where x.address != null
|only scan
|"Exists" and "IsNotNull" represent the same functionality and can be used interchangeably, objects and fields exist
when their value is not equal to null.

|LessThan, IsLessThan a|
[source,java]
----
findByAddressLessThan(Address address)
----
|...where x.address < ?
|only scan
|Find records where `address` bin value (POJOs are stored in AerospikeDB as maps) has fewer elements or has
a corresponding element lower in ordering than in the given argument.
See https://docs.aerospike.com/server/guide/data-types/cdt-ordering#map[information about ordering].

|LessThanEqual, IsLessThanEqual a|
[source,java]
----
findByAddressLessThanEqual(Address address)
----
|...where x.address < = ?
|only scan
|Find records where `address` bin value (POJOs are stored in AerospikeDB as maps) has smaller or the same amount of
elements or has each corresponding element lower in ordering or the same as in the given argument.
See https://docs.aerospike.com/server/guide/data-types/cdt-ordering#map[information about ordering].

|GreaterThan, IsGreaterThan a|
[source,java]
----
findByAddressGreaterThan(Address address)
----
|...where x.address > ?
|only scan
|Find records where `address` bin value (POJOs are stored in AerospikeDB as maps) has more elements or has
a corresponding element higher in ordering than in the given argument.
See https://docs.aerospike.com/server/guide/data-types/cdt-ordering#map[information about ordering].

|GreaterThanEqual, IsGreaterThanEqual a|
[source,java]
----
findByAddressGreaterThanEqual(Address address)
----
|...where x.address >= ?
|only scan
|Find records where `address` bin value (POJOs are stored in AerospikeDB as maps) has larger or the same amount
of elements or has each corresponding element higher in ordering or the same as in the given argument.
See https://docs.aerospike.com/server/guide/data-types/cdt-ordering#map[information about ordering].

|Between, IsBetween a|
[source,java]
----
findByAddressBetween(Address lowerLimit, Address upperLimit)
----
|...where x.address between ? (inclusive) and ? (exclusive)
|only scan
|Find records where `address` bin value (POJOs are stored in AerospikeDB as maps) is in the range between
the given arguments. See https://docs.aerospike.com/server/guide/data-types/cdt-ordering#map[information about ordering].

|And a|
[source,java]
----
findByAddressAndFriend(QueryParam address, QueryParam friend)
----
|...where x.address = ? and x.friend = ?
|only scan
|

|Or a|
[source,java]
----
findByAddressOrFriend(QueryParam address, QueryParam friend)
----
|...where x.address = ? or x.friend = ?
|only scan
|
|===
