= Query Modification

== Query Modifiers

[width="100%",cols="<12%,<25%,<30%,<25%",options="header",]
|===
|Keyword |Sample |Snippet |Notes

|IgnoreCase |findByLastNameIgnoreCase |...where UPPER(x.lastName) = UPPER(?) |

|OrderBy |findByLastNameOrderByFirstNameDesc |...where x.lastName = ? order by x.firstName desc
|Ordering is done applicatively in Spring Data Aerospike as post-processing of the query results.
If there is a secondary index created for the ordering bin (in this example `firstName`), it is not used,
indexes are relevant only for the main query part before `OrderBy`.
Ordering affects performance depending on the amount of query results
|===

== Limiting Query Results

[width="100%",cols="<12%,<25%,<30%",options="header",]
|===
|Keyword |Sample |Snippet
|First |findFirstByAge | select top 1 where x.age = ?

|First N |findFirst3ByAge | select top 3  where x.age = ?

|Top |findTopByLastNameStartingWith | select top 1 where x.lastName like 'abc%' = ?

|Top N |findTop4ByLastNameStartingWith | select top 4  where x.lastName like 'abc%'

|Distinct | findDistinctByFirstNameContaining | select distinct ... where x.firstName like 'abc%'
|===

NOTE: Limiting of queries results is done applicatively in Spring Data Aerospike as post-processing of query results.
It can affect performance depending on the amount of query results and limiting parameters

[[find-using-query]]
== Find Using Query

User can perform a custom `Query` for finding matching entities in the Aerospike database.
A `Query` can be created using a `Qualifier` which represents an expression.
It may contain other qualifiers and combine them using either `AND` or `OR`.

`Qualifier` can be created for regular bins, metadata and ids (primary keys).
Below is an example of different variations:

[source,java]
----
    // creating an expression "firsName is equal to John"
    Qualifier firstNameEqJohn = Qualifier.builder()
        .setPath("firstName")
        .setFilterOperation(FilterOperation.EQ)
        .setValue("John")
        .build();
    result = repository.findUsingQuery(new Query(firstNameEqJohn));
    assertThat(result).containsOnly(john);

    // creating an expression "primary key is equal to person's id"
    Qualifier keyEqJohnsId = Qualifier.idEquals(john.getId());
    result = repository.findUsingQuery(new Query(keyEqJohnsId));
    assertThat(result).containsOnly(john);

    // creating an expression "since_update_time metadata value is less than 50 seconds"
    Qualifier sinceUpdateTimeLt50Seconds = Qualifier.metadataBuilder()
        .setMetadataField(SINCE_UPDATE_TIME)
        .setFilterOperation(FilterOperation.LT)
        .setValue(50000L)
        .build();
    result = repository.findUsingQuery(new Query(sinceUpdateTimeLt50Seconds));
    assertThat(result).contains(john);

    // expressions are combined using AND
    result = repository.findUsingQuery(new Query(Qualifier.and(firstNameEqJohn, keyEqJohnsId, sinceUpdateTimeLt50Seconds)));
    assertThat(result).containsOnly(john);
----