[[aerospike.query_methods.id]]
= Id Repository Queries

*Repository reading queries featuring id equality* (like `findById()`, `findByIds()`, `findByFirstNameAndId()`, `findAllById()`,
`countById()`, `existsById()` etc.) utilize `get` operation of the underlying Java client (`client.get()`).

[width="100%",cols="<7%,<30%,<25%,<10%,<20%",options="header",]
|===
|Keyword |Repository query sample |Snippet |Uses secondary index |Notes

|no keyword a|
[source,java]
----
findById(String id)
----
|...where x.PK = ?
|uses primary key directly
| This query utilizes `get` operation of Java client

|Like a|
[source,java]
----
findByIdLike(String idPattern)
----
|...where x.PK like ?
|only scan
|`idPattern` must be a String. This query utilizes `query` operation of Java client

|And a|
[source,java]
----
findByIdAndFirstName(QueryParam ids, QueryParam firstName)

findByIdLikeAndFirstName(QueryParam id, QueryParam firstName)
----
|...where x.PK = ? and x.firstName = ?

...where x.PK like ? and x.firstName = ?
|depending on each part of query
|

|===

== Runnable ID and Bin Criteria Examples

The runnable examples include derived and custom queries where an id criterion is combined with a regular bin criterion.

=== Derived Query Methods

Derived query methods wrap the id part in `QueryParam`, which can carry either one id or several ids.

[source,java]
----
include::{examples-java}/org/springframework/data/aerospike/examples/blocking/querymethods/repository/QueryMethodsMovieRepository.java[tag=blocking-derived-query-id-bin-methods,indent=0]
----

[source,java]
----
include::{examples-java}/org/springframework/data/aerospike/examples/blocking/querymethods/BlockingRepositoryDerivedIdAndBinQueryExample.java[tag=blocking-derived-query-id-bin-usage,indent=0]
----

[source,java]
----
include::{examples-java}/org/springframework/data/aerospike/examples/reactive/querymethods/repository/ReactiveQueryMethodsMovieRepository.java[tag=reactive-derived-query-id-bin-methods,indent=0]
----

[source,java]
----
include::{examples-java}/org/springframework/data/aerospike/examples/reactive/querymethods/ReactiveRepositoryDerivedIdAndBinQueryExample.java[tag=reactive-derived-query-id-bin-usage,indent=0]
----

=== Custom Queries

Custom queries use `Qualifier.idEquals` or `Qualifier.idIn` with a regular bin qualifier.

[source,java]
----
include::{examples-java}/org/springframework/data/aerospike/examples/blocking/customquery/programmatic/ProgrammaticCustomQueryIdAndBinExample.java[tag=blocking-custom-query-id-bin-usage,indent=0]
----

[source,java]
----
include::{examples-java}/org/springframework/data/aerospike/examples/reactive/customquery/ReactiveProgrammaticCustomQueryIdAndBinExample.java[tag=reactive-custom-query-id-bin-usage,indent=0]
----
