= Query Methods

Spring Data Aerospike supports defining queries by method name in the Repository interface so that the implementation is generated. The format of method names is fairly flexible, comprising a verb and criteria.

Some of the verbs include `find`, `query`, `read`, `get`, `count` and `delete`. For example, `countByLastName`, `findByFirstName` etc.

For more details refer to SpringData documentation: <<query-by-example, Query By Example>>.

[width="100%",cols="<12%,<25%,<25%",options="header",]
|===
|Keyword |Sample |Snippet
|And |findByLastNameAndFirstName |...where x.lastName = ? and x.firstName = ?

|Or |findByLastNameOrFirstName |...where x.lastName = ? or x.firstName = ?

|Is, Equals |findByLastName, findByLastNameIs, findByLastNameEquals |...where x.lastName = ?

|Between |findByDateOfBirthBetween |...where x.dateOfBirth between ? and ?

|LessThan |findByAgeLessThan |...where x.age < ?

|LessThanEqual |findByAgeLessThanEqual |...where x.age <= ?

|GreaterThan |findByAgeGreaterThan |...where x.age > ?

|GreaterThanEqual |findByAgeGreaterThanEqual |...where x.age >= ?

|After |findByDateOfBirthAfter |...where x.dateOfBirth > ?

|Before |findByDateOfBirthBefore |...where x.dateOfBirth < ?

|Like, MatchesRegex |findByLastNameLike

findByLastNameMatchesRegex

|...where x.lastName like ?

|StartingWith |findByLastNameStartingWith |...where x.lastName like 'abc%'

|EndingWith |findByLastNameEndingWith |...where x.lastName like '%abc'

|Containing |findByLastNameContaining |...where x.lastName like '%abc%

|Not Containing |findByLastNameNotContaining |...where x.lastName not like '%abc%

|OrderBy |findByLastNameOrderByFirstNameDesc |...where x.lastName = ? order by x.firstName desc

|Not |findByLastNameNot |...where x.lastName <> ?

|In |findByLastNameIn(Collection<String>) |...where x.lastName in ?

|Not In |findByLastNameNotIn(Collection<String>) |...where x.lastName not in ?

|IgnoreCase |findByLastNameIgnoreCase |...where UPPER(x.lastName) = UPPER(?)

|Exists

IsNotNull

|findByAddressExists()

findByObjectIsNotNull()

findByObjectFieldExists()

|...where address exists and != null

...where object exists and != null

...where object.field exists and != null

("Exists" and "IsNotNull" represent the same functionality and can be used interchangeably as bins/fields exist when have a value not equal to null)

|IsNull |findByObjectIsNull()

findByObjectFieldIsNull()

|...where object = null

...where object.field = null

(bins/fields exist when have a value not equal to null)

|True |findByEnabledTrue() |...where x.enabled = true

|False |findByOptOutFalse() |...where x.optOut = false

|FindUsingQuery |findUsingQuery(query) |find matching entities (see xref:#find-using-query[find using query]])
|===

Below is an example of an interface with several query methods:

[source,java]
----
public interface PersonRepository extends AerospikeRepository<Person, Long> {
    List<Person> findByLastName(String lastName);
    List<Person> findByLastNameContaining(String lastName);
    List<Person> findByLastNameStartingWith(String lastName);
    List<Person> findByLastNameAndFirstNameContaining(String lastName, String firstName);
    List<Person> findByAgeBetween(long startAge, long endAge);
    Optional<Person> findById(Long id);
}
----

== Limiting Query Results
[width="100%",cols="<12%,<25%,<25%",options="header",]
|===
|Keyword |Sample |Snippet
|First |findFirstByAge | select top 1 where x.age = ?

|First N |findFirst3ByAge | select top 3  where x.age = ?

|Top |findTopByLastNameStartingWith | select top 1 where x.lastName like 'abc%' = ?

|Top N |findTop4ByLastNameStartingWith | select top 4  where x.lastName like 'abc%'

|Distinct | findDistinctByFirstNameContaining | select distinct ... where x.firstName like 'abc%'
|===

[[find-using-query]]
== Find Using Query

User can perform a custom `Query` for finding matching entities in the Aerospike database. A `Query` can be created using a `Qualifier` which represents an expression. It may contain other qualifiers and combine them using either `AND` or `OR`.

`Qualifier` can be created for regular bins, metadata and ids (primary keys). Below is an example of different variations:

[source,java]
----
    // creating an expression "firsName is equal to John"
    Qualifier firstNameEqJohn = Qualifier.builder()
        .setField("firstName")
        .setFilterOperation(FilterOperation.EQ)
        .setValue1(Value.get("John"))
        .build();
    result = repository.findUsingQuery(new Query(firstNameEqJohn));
    assertThat(result).containsOnly(john);

    // creating an expression "primary key is equal to person's id"
    Qualifier keyEqJohnsId = Qualifier.idEquals(john.getId());
    result = repository.findUsingQuery(new Query(keyEqJohnsId));
    assertThat(result).containsOnly(john);

    // creating an expression "since_update_time metadata value is less than 50 seconds"
    Qualifier sinceUpdateTimeLt50Seconds = Qualifier.metadataBuilder()
        .setMetadataField(SINCE_UPDATE_TIME)
        .setFilterOperation(FilterOperation.LT)
        .setValue1AsObj(50000L)
        .build();
    result = repository.findUsingQuery(new Query(sinceUpdateTimeLt50Seconds));
    assertThat(result).contains(john);

    // expressions are combined using AND
    result = repository.findUsingQuery(new Query(Qualifier.and(firstNameEqJohn, keyEqJohnsId, sinceUpdateTimeLt50Seconds)));
    assertThat(result).containsOnly(john);
----