[[aerospike.template]]
= Aerospike Template

Aerospike Template provides a set of features for interacting with the database.
It allows lower-level access than a Repository and also serves as the foundation for repositories.

Template is the central support class for Aerospike database operations.
It provides the following functionality:

- Methods to interact with the database
- Mapping between Java objects and Aerospike Bins (see <<aerospike.object-mapping, Object Mapping>>)
- Providing connection callback
- Translating exceptions into Spring's technology-agnostic
https://docs.spring.io/spring/docs/current/spring-framework-reference/html/dao.html#dao-exceptions[DAO exceptions hierarchy]

[[aerospike-template.instantiating]]
== Instantiating AerospikeTemplate

If you are subclassing `AbstractAerospikeDataConfiguration` then the `aerospikeTemplate` bean is already present
in your context, and you can use it.

[source,java]
----
include::{examples-java}/org/springframework/data/aerospike/examples/blocking/template/config/TemplateAerospikeConfiguration.java[tag=template-bean,indent=0]
----

An alternative is to instantiate it yourself, you can see the bean in `AbstractAerospikeDataConfiguration`.

In case if you need to use custom `WritePolicy`, the `persist` operation can be used.

For CAS updates `save` operation must be used.

== Methods for interacting with database

`AerospikeOperations` interface provides operations for interacting with the database (`exists`, `find`, `insert`,
`update` etc.) as well as basic operations with indexes: `createIndex`, `deleteIndex`, `indexExists`.

The names of operations are typically self-descriptive. To read from Aerospike you can use `findById`, `findByIds`
and `find` methods, to delete - `delete` methods, and so on.

[source,java]
----
include::{examples-java}/org/springframework/data/aerospike/examples/blocking/template/BlockingTemplateExample.java[tag=template-find-by-ids,indent=0]
----

For indexed documents use `find` with provided `Query` object.

[source,java]
----
include::{examples-java}/org/springframework/data/aerospike/examples/blocking/template/BlockingTemplateExample.java[tag=template-query-count-exists,indent=0]
----

== Example

The simple case of using the save operation is to save a POJO.

NOTE: For more information about Id property when inserting or saving see
xref:#mapping-conventions-id-field[Mapping Conventions: Id Field] for more information.

[source,java]
----
include::{examples-java}/org/springframework/data/aerospike/examples/blocking/template/entity/TemplateMovieDocument.java[tag=template-entity]
----

[source,java]
----
include::{examples-java}/org/springframework/data/aerospike/examples/blocking/template/BlockingTemplateExample.java[tag=template-save,indent=0]
----

Template also supports projections and record-level mutations:

[source,java]
----
include::{examples-java}/org/springframework/data/aerospike/examples/blocking/template/BlockingTemplateExample.java[tag=template-projection,indent=0]
----

[source,java]
----
include::{examples-java}/org/springframework/data/aerospike/examples/blocking/template/BlockingTemplateExample.java[tag=template-bin-mutations,indent=0]
----

Use `update` to write selected fields only, and `persist` when a custom `WritePolicy` is needed:

[source,java]
----
include::{examples-java}/org/springframework/data/aerospike/examples/blocking/template/BlockingTemplateExample.java[tag=template-partial-update,indent=0]
----

[source,java]
----
include::{examples-java}/org/springframework/data/aerospike/examples/blocking/template/BlockingTemplateExample.java[tag=template-custom-write-policy,indent=0]
----
