[[aerospike.template]]
== Aerospike Template

Aerospike Template provides a set of features for interacting with the database. It allows lower-level access than a Repository and also serves as the foundation for repositories.

Template is the central support class for Aerospike database operations. It provides the following functionality:

- Mapping between Java objects and Aerospike Bins (see Mapping)
- Methods to interact with the database
- Connection callback
- Translating exceptions into Spring's technology-agnostic https://docs.spring.io/spring/docs/current/spring-framework-reference/html/dao.html#dao-exceptions[DAO exceptions hierarchy]

[[aerospike-template.instantiating]]
=== Instantiating AerospikeTemplate

If you are subclassing `AbstractAerospikeDataConfiguration` then the `aerospikeTemplate` bean is already present in your context, and you can use it.

[source, java]
----
@Autowired
protected AerospikeTemplate template;
----

An alternative is to instantiate it yourself, you can see the bean in `AbstractAerospikeDataConfiguration`.

In case if you need to use custom `WritePolicy`, the `persist` operation can be used

For CAS updates `save` operation must be used.

=== Methods for interacting with database

`AerospikeTemplate` provides operations for interacting with the database (`exists`, `find`, `insert`, `update` etc.) as well as basic operations with indexes: `createIndex`, `deleteIndex`, `indexExists`.

The names of operations are typically self-descriptive. For reading from DB you can use `findById` or `findByIds` operations, to delete documents use `delete` methods etc.

[source, java]
----
template.findById(id, Person.class)
----

For indexed documents use `find` with provided `Query` object.

[source, java]
----
Stream<Person> result = template.find(query, Person.class);
assertThat(result).hasSize(6);
----

=== Example

The simple case of using the save operation is to save a POJO.

NOTE: For more information about Id property when inserting or saving see xref:#mapping-conventions-id-field[Mapping Conventions: Id Field] for more information.

[source, java]
----
public class Person {

    @Id
    private String id;
    private String firstName;
    private String lastName;
    private int age;
}
----

[source, java]
----
template.insert(new Person(id, "John", 50));

long count = template.count
            (new Query
                    (new AerospikeCriteria
                        (new Qualifier.QualifierBuilder()
                            .setFilterOperation(FilterOperation.EQ)
                            .setField("firstName")
                            .setValue1(Value.get("John"))
                        )
                    ),
                Person.class
            );

        assertThat(count).isEqualTo(3);
----
