name: Get version
description: Gets the release version from the Maven POM

runs:
  using: composite
  steps:
    - name: Get release version
      id: get-release-version
      shell: bash
      run: |
        echo release-version="$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_OUTPUT

outputs:
  release-version:
    description: The release version
    value: ${{ steps.get-release-version.outputs.release-version }}
