name: Promote release bundle to DEV

permissions:
  id-token: write

on:
  workflow_dispatch:
    inputs:
      version:
        description: Version to be promoted
        required: true
        type: string

jobs:
  promote-to-dev:
    name: Promote to DEV
    runs-on: ${{ vars.BUILD_CONTAINER_DISTRO_VERSION }}
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@20cf305ff2072d973412fa9b1e3a4f227bda3c76 # v2.14.0
        with:
          egress-policy: audit

      - name: Setup JFrog CLI
        uses: step-security/setup-jfrog-cli@a6b41f8338bea0983ddff6bd4ede7d2dcd81e1fa # v4.8.1
        env:
          JF_URL: ${{ vars.JFROG_PLATFORM_URL }}
          JF_PROJECT: ${{ vars.JFROG_PROJECT }}
        with:
          oidc-provider-name: ${{ vars.OIDC_PROVIDER_NAME }}
          oidc-audience: ${{ vars.OIDC_AUDIENCE }}

      - name: Promoting release bundle to DEV
        uses: aerospike/shared-workflows/.github/actions/promote-release-bundle@f6bb565e7d31fa3013a1a75c5f80aed44c3bde5c # v3.4.1
        with:
          bundle-name: spring-data-aerospike
          version: ${{ inputs.version }}
          environment: DEV
          jf-project: ${{ vars.JFROG_PROJECT }}
